sudo: required


language: php

notifications:
  email:
    on_success: never
    on_failure: change


cache:
  directories:
    - $HOME/.composer/cache

env:
  - PHP_IMAGE_TAG=7.2-alpine WORDPRESS_VERSION=latest
  - PHP_IMAGE_TAG=7.2-alpine WORDPRESS_VERSION=trunk
  - PHP_IMAGE_TAG=7.2-alpine WORDPRESS_VERSION=4.8
  - PHP_IMAGE_TAG=7.2-alpine WORDPRESS_VERSION=4.7
  - PHP_IMAGE_TAG=7.1-alpine WORDPRESS_VERSION=latest
  - PHP_IMAGE_TAG=7.0-alpine WORDPRESS_VERSION=latest
  - PHP_IMAGE_TAG=5.6-alpine WORDPRESS_VERSION=latest

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer update
  - composer wp-install

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      composer wp-tests
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      phpcs
    fi
